import { CSSProperties } from "react";
export const styles: { [key: string]: CSSProperties } = {
  container: {
    width: 280,
    height: 360,
    backgroundColor: "#fff",
    padding: 16,
    margin: "auto",
    position: "absolute",
    top: "12%",
    left: "40%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    textAlign: "center",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  inputBox: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    border: "2px solid #e9e9f4",
    padding: 4,
    width: 242,
    height: 32,
  },
  input: {
    backgroundColor: "#fff",
    color: "#000",
    border: 0,
    height: "100%",
    width: "100%",
    outline: "none",
  },
  column: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
  },
  eye: {
    background: "none",
    borderWidth: 0,
    outline: "none",
    padding: 2,
    margin: 2,
  },
  eyeIcon: { color: "#000000", height: 16 },
  rememberBox: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    width: 258,
  },
  rememberInput: {
    background: "none",
    height: 16,
    width: 16,
    color: "#ffffff",
    border: 0,
  },
  singIn: {
    backgroundColor: "#18aa6b",
    padding: 12,
    width: 250,
    borderRadius: 0,
  },
};
