export const styles = {
  form: {
    width: 280,
    height: 360,
    backgroundColor: "#fff",
    padding: 16,
    margin: "auto",
    position: "absolute",
    top: "12%",
    left: "40%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    textAlign: "center",
  },
  input: {
    container: {
      display: "flex",
      flexDirection: "column",
      alignItems: "flex-start",
    },
    box: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      border: "2px solid #b9b9b9",
      padding: 4,
      width: 242,
      height: 32,
    },
    username: {
      backgroundColor: "#fff",
      color: "#000",
      border: 0,
      height: "100%",
      width: "100%",
      outline: "none",
    },
    password: {
      backgroundColor: "#fff",
      color: "#000",
      border: 0,
      height: "100%",
      width: "100%",
      outline: "none",
    },
    eye: {
      background: "none",
      borderWidth: 0,
      outline: "none",
      padding: 2,
      margin: 2,
    },
    icon: { color: "#000000", height: 16 },
  },

  checkBox: {
    container: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      width: 258,
    },
    input: {
      background: "none",
      height: 16,
      width: 16,
      color: "#ffffff",
      border: 0,
    },
  },
  button: {
    backgroundColor: "#18aa6b",
    padding: 12,
    width: 250,
    borderRadius: 0,
  },
};
